[package]
name = "sequoia"
version = "0.1.0"
authors = ["MrKomodoDragon <svrchn921@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
